<a href="https://colab.research.google.com/github/Krishna-matic/python_practice/blob/main/Gender_dataset_decisionTree.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("/content/drive/MyDrive/DataSetForpython/Transformed Data Set - Sheet1.csv")

In [3]:
df.head()

,Favorite Color,Favorite Music Genre,Favorite Beverage,Favorite Soft Drink,Gender
0,Cool,Rock,Vodka,7UP/Sprite,F
1,Neutral,Hip hop,Vodka,Coca Cola/Pepsi,F
2,Warm,Rock,Wine,Coca Cola/Pepsi,F
3,Warm,Folk/Traditional,Whiskey,Fanta,F
4,Cool,Rock,Vodka,Coca Cola/Pepsi,F

In [4]:
df['Favorite Beverage'].value_counts()

Favorite Beverage
Doesn't drink    14
Beer             13
Other            11
Wine             10
Vodka             9
Whiskey           9
Name: count, dtype: int64

In [5]:
beverage_mapping = {
    "Doesn't drink": 0,
    "Beer": 1,
    "Wine": 2,
    "Vodka": 3,
    "Whiskey": 4,
    "Other": 5
}

df["Favorite Beverage"] = df["Favorite Beverage"].map(beverage_mapping)

In [11]:
df.columns

Index(['Favorite Color', 'Favorite Music Genre', 'Favorite Beverage',
       'Favorite Soft Drink', 'Gender'],
      dtype='object')

In [12]:
df['Favorite Music Genre'].value_counts()

Favorite Music Genre
Rock                19
Pop                 17
Hip hop              8
Electronic           8
R&B and soul         6
Folk/Traditional     4
Jazz/Blues           4
Name: count, dtype: int64

In [13]:
music_mapping = {
    "Rock": 0,
    "Pop": 1,
    "Hip hop": 2,
    "Electronic": 3,
    "R&B and soul": 4,
    "Folk/Traditional": 5,
    "Jazz/Blues": 6
}

df["Favorite Music Genre"] = df["Favorite Music Genre"].map(music_mapping)

In [14]:
df['Favorite Color'].value_counts()

Favorite Color
Cool       37
Warm       22
Neutral     7
Name: count, dtype: int64

In [15]:
color_mapping = {
    "Cool": 0,
    "Neutral": 1,
    "Warm": 2
}

df["Favorite Color"] = df["Favorite Color"].map(color_mapping)

In [16]:
df['Favorite Soft Drink'].value_counts()

Favorite Soft Drink
Coca Cola/Pepsi    32
Fanta              14
7UP/Sprite         13
Other               7
Name: count, dtype: int64

In [17]:
soft_drink_mapping = {
    "Coca Cola/Pepsi": 0,
    "Fanta": 1,
    "7UP/Sprite": 2,
    "Other": 3
}
df["Favorite Soft Drink"] = df["Favorite Soft Drink"].map(soft_drink_mapping)

In [18]:
df['Gender'].value_counts()

Gender
F    33
M    33
Name: count, dtype: int64

In [19]:
df['Gender'] = df['Gender'].map({"F":0,"M":1})

In [20]:
df.head()

,Favorite Color,Favorite Music Genre,Favorite Beverage,Favorite Soft Drink,Gender
0,0,0,3,2,0
1,1,2,3,0,0
2,2,0,2,0,0
3,2,5,4,1,0
4,0,0,3,0,0

In [23]:
X = df.drop(['Gender'],axis = 1 )
y = df['Gender']

In [24]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [25]:
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier(random_state=42)

dt.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

In [26]:
y_pred = dt.predict(X_test)

In [27]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

print("Accuracy :", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred, average='weighted'))
print("Recall   :", recall_score(y_test, y_pred, average='weighted'))
print("F1 Score :", f1_score(y_test, y_pred, average='weighted'))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report")
print(classification_report(y_test, y_pred))

Accuracy : 0.6428571428571429
Precision: 0.6749999999999999
Recall   : 0.6428571428571429
F1 Score : 0.625668449197861

Confusion Matrix
[[3 4]
 [1 6]]

Classification Report
              precision    recall  f1-score   support

           0       0.75      0.43      0.55         7
           1       0.60      0.86      0.71         7

    accuracy                           0.64        14
   macro avg       0.68      0.64      0.63        14
weighted avg       0.67      0.64      0.63        14

In [28]:
y_train_pred = dt.predict(X_train)

In [29]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

print("========== Training Performance ==========\n")

print("Accuracy :", accuracy_score(y_train, y_train_pred))
print("Precision:", precision_score(y_train, y_train_pred, average='weighted'))
print("Recall   :", recall_score(y_train, y_train_pred, average='weighted'))
print("F1 Score :", f1_score(y_train, y_train_pred, average='weighted'))

print("\nConfusion Matrix")
print(confusion_matrix(y_train, y_train_pred))

print("\nClassification Report")
print(classification_report(y_train, y_train_pred))

========== Training Performance ==========

Accuracy : 0.9423076923076923
Precision: 0.9482758620689655
Recall   : 0.9423076923076923
F1 Score : 0.9421150278293136

Confusion Matrix
[[26  0]
 [ 3 23]]

Classification Report
              precision    recall  f1-score   support

           0       0.90      1.00      0.95        26
           1       1.00      0.88      0.94        26

    accuracy                           0.94        52
   macro avg       0.95      0.94      0.94        52
weighted avg       0.95      0.94      0.94        52